"""empty message

Revision ID: 237218883b48
Revises: 31e3b753bfcb
Create Date: 2023-04-23 12:59:36.963539

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy import inspect

# revision identifiers, used by Alembic.
revision = '237218883b48'
down_revision = '31e3b753bfcb'
branch_labels = None
depends_on = None


def upgrade():
    bind = op.get_bind()
    inspector = inspect(bind)
    # ### commands auto generated by Alembic - please adjust! ###
    if 'mock_interviews_requests' not in inspector.get_table_names(schema="interviews_passing"):

        op.create_table('mock_interviews_requests',
        sa.Column('event_id', sa.String(), nullable=False),
        sa.Column('token', sa.String(), nullable=True),
        sa.Column('full_name', sa.String(), nullable=True),
        sa.Column('email_address', sa.String(), nullable=True),
        sa.Column('resume_link', sa.String(), nullable=True),
        sa.Column('is_v3', sa.Boolean(), nullable=True),
        sa.Column('region', sa.String(), nullable=True),
        sa.Column('date_of_interview', sa.Date(), nullable=True),
        sa.Column('company_name', sa.String(), nullable=True),
        sa.Column('job_title', sa.String(), nullable=True),
        sa.Column('job_description', sa.String(), nullable=True),
        sa.Column('job_location', sa.String(), nullable=True),
        sa.Column('event_stage', sa.String(), nullable=True),
        sa.Column('had_home_assignment', sa.Boolean(), nullable=True),
        sa.Column('home_assignment_questions_link', sa.String(), nullable=True),
        sa.Column('home_assignment_answers_link', sa.String(), nullable=True),
        sa.Column('source_1', sa.String(), nullable=True),
        sa.Column('source_2', sa.String(), nullable=True),
        sa.Column('source_3', sa.String(), nullable=True),
        sa.Column('is_pass', sa.String(), nullable=True),
        sa.Column('mentor', sa.String(), nullable=True),
        sa.Column('date_of_mock_interview', sa.Date(), nullable=True),
        sa.Column('recording_link', sa.String(), nullable=True),
        sa.Column('stage_in_funnel', sa.String(), nullable=True),
        sa.Column('post_interview_meeting_date', sa.DateTime(), nullable=True),
        sa.Column('submission_time', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('event_id'),
        sa.UniqueConstraint('event_id'),
        schema='interviews_passing'
        )
        op.drop_table('interviews_passing.mock_interviews_requests')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interviews_passing.mock_interviews_requests',
    sa.Column('event_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('token', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('full_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('email_address', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('resume_link', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_v3', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('region', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('date_of_interview', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('company_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('job_title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('job_description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('job_location', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('event_stage', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('had_home_assignment', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('home_assignment_questions_link', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('home_assignment_answers_link', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('source_1', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('source_2', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('source_3', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_pass', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('mentor', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('date_of_mock_interview', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('recording_link', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('stage_in_funnel', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('post_interview_meeting_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('submission_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('event_id', name='interviews_passing.mock_interviews_requests_pkey'),
    sa.UniqueConstraint('event_id', name='interviews_passing.mock_interviews_requests_event_id_key')
    )
    op.drop_table('mock_interviews_requests', schema='interviews_passing')
    # ### end Alembic commands ###
