"""empty message

Revision ID: 31e3b753bfcb
Revises: caec4d48214d
Create Date: 2023-04-23 12:53:52.131402

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31e3b753bfcb'
down_revision = 'caec4d48214d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interviews_passing.mock_interviews_requests', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['event_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interviews_passing.mock_interviews_requests', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
