"""empty message

Revision ID: 6af7d62ea1c2
Revises: 865d2a6f9d49
Create Date: 2023-03-26 23:01:23.881760

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6af7d62ea1c2'
down_revision = '865d2a6f9d49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('webhooks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('job_id', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('webhooks', schema=None) as batch_op:
        batch_op.drop_column('job_id')

    # ### end Alembic commands ###
