"""empty message

Revision ID: 865d2a6f9d49
Revises: ad0646516fef
Create Date: 2023-03-09 12:53:14.185557

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '865d2a6f9d49'
down_revision = 'ad0646516fef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('communications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('job_id', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('communications', schema=None) as batch_op:
        batch_op.drop_column('job_id')

    # ### end Alembic commands ###
