"""empty message

Revision ID: ad0646516fef
Revises: c1cf41c45892
Create Date: 2023-03-03 23:43:04.465000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad0646516fef'
down_revision = 'c1cf41c45892'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_slack_ids', schema=None) as batch_op:
        batch_op.drop_column('gender')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_slack_ids', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gender', sa.VARCHAR(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
