"""empty message

Revision ID: c1cf41c45892
Revises: fd95e1ad7e24
Create Date: 2023-03-03 23:41:13.907881

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1cf41c45892'
down_revision = 'fd95e1ad7e24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_slack_ids', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gender', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_slack_ids', schema=None) as batch_op:
        batch_op.drop_column('gender')

    # ### end Alembic commands ###
