"""empty message

Revision ID: caec4d48214d
Revises: 6af7d62ea1c2
Create Date: 2023-03-28 00:18:38.866038

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'caec4d48214d'
down_revision = '6af7d62ea1c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('huntr_job_mvmnt', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_huntr_job_mvmnt_id', ['huntr_job_mvmnt_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('huntr_job_mvmnt', schema=None) as batch_op:
        batch_op.drop_constraint('unique_huntr_job_mvmnt_id', type_='unique')

    # ### end Alembic commands ###
